default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rap
  password:

development:
  <<: *default
  database: rrr_development

real:
  <<: *default
  database: rrr_real

test:
  <<: *default
  database: rrr_test

